[build-system]
requires = ["setuptools==84.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hivebox"
version = "0.3.0"
description = "REST API for beekeepers based on openSenseMap data"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = "==3.13.*"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]==0.141.1",
    "httpx==0.28.1",
    "prometheus-client==0.26.0",
    "prometheus-fastapi-instrumentator==8.1.0",
]

[project.optional-dependencies]
test = [
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
    "pytest-httpx==0.36.2",
]
quality = [
    "bump-my-version==1.5.1",
    "build==1.5.0",
    "mypy==2.3.1",
    "pylint==4.0.7",
    "ruff==0.16.4",
    "twine==7.0.0",
]

[tool.fastapi]
entrypoint = "src.main:app"

[tool.setuptools.packages.find]
include = ["src*"]

[tool.pytest.ini_options]
addopts = ["--strict-config", "--strict-markers"]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
fail_under = 90
show_missing = true

[tool.mypy]
files = ["src", "tests"]
python_version = "3.13"
strict = true

[tool.pylint.main]
persistent = false
py-version = "3.13"

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.bumpversion]
allow_dirty = false
commit = false
tag = false
push_tag = false
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "kubernetes/app/deployment.yaml"
search = "image: hivebox:v{current_version}"
replace = "image: hivebox:v{new_version}"

[[tool.bumpversion.files]]
filename = "tests/test_version.py"
search = '{{"version": "{current_version}"}}'
replace = '{{"version": "{new_version}"}}'

[[tool.bumpversion.files]]
filename = "tests/integration/test_api.py"
search = '{{"version": "{current_version}"}}'
replace = '{{"version": "{new_version}"}}'

[[tool.bumpversion.files]]
filename = "README.md"
search = '{{"version":"{current_version}"}}'
replace = '{{"version":"{new_version}"}}'

[[tool.bumpversion.files]]
filename = "README.md"
search = "hivebox:v{current_version}"
replace = "hivebox:v{new_version}"
